# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'starwarscharacterinfo.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(650, 500))
        MainWindow.setMaximumSize(QtCore.QSize(650, 500))
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("QMainWindow {\n"
"background-color: black;\n"
"}\n"
"\n"
"QLabel {\n"
"color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
"background-color: black;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.name_header = QtWidgets.QLabel(self.centralwidget)
        self.name_header.setGeometry(QtCore.QRect(10, 0, 631, 81))
        self.name_header.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(42)
        self.name_header.setFont(font)
        self.name_header.setAlignment(QtCore.Qt.AlignCenter)
        self.name_header.setObjectName("name_header")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 100, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 150, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(250, 100, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(250, 150, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(450, 100, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(450, 150, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(80, 200, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(30, 250, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(90, 300, 41, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(30, 350, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(40, 400, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(260, 300, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(270, 350, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(270, 400, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(470, 300, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(430, 350, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(450, 400, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(17, 70, 620, 20))
        self.line_2.setMidLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(17, 220, 621, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setAutoFillBackground(False)
        self.line.setStyleSheet("color: rgb(169, 171, 171);")
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(1)
        self.line.setMidLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.label_height = QtWidgets.QLabel(self.centralwidget)
        self.label_height.setGeometry(QtCore.QRect(140, 100, 101, 16))
        self.label_height.setObjectName("label_height")
        self.label_mass = QtWidgets.QLabel(self.centralwidget)
        self.label_mass.setGeometry(QtCore.QRect(140, 150, 91, 16))
        self.label_mass.setObjectName("label_mass")
        self.label_gender = QtWidgets.QLabel(self.centralwidget)
        self.label_gender.setGeometry(QtCore.QRect(140, 200, 101, 16))
        self.label_gender.setObjectName("label_gender")
        self.label_haircolor = QtWidgets.QLabel(self.centralwidget)
        self.label_haircolor.setGeometry(QtCore.QRect(330, 100, 101, 16))
        self.label_haircolor.setObjectName("label_haircolor")
        self.label_skincolor = QtWidgets.QLabel(self.centralwidget)
        self.label_skincolor.setGeometry(QtCore.QRect(330, 150, 101, 16))
        self.label_skincolor.setObjectName("label_skincolor")
        self.label_eyecolor = QtWidgets.QLabel(self.centralwidget)
        self.label_eyecolor.setGeometry(QtCore.QRect(530, 100, 101, 16))
        self.label_eyecolor.setObjectName("label_eyecolor")
        self.label_birthyear = QtWidgets.QLabel(self.centralwidget)
        self.label_birthyear.setGeometry(QtCore.QRect(530, 150, 101, 16))
        self.label_birthyear.setObjectName("label_birthyear")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(140, 300, 101, 16))
        self.label_name.setObjectName("label_name")
        self.label_rotationperiod = QtWidgets.QLabel(self.centralwidget)
        self.label_rotationperiod.setGeometry(QtCore.QRect(140, 350, 111, 16))
        self.label_rotationperiod.setObjectName("label_rotationperiod")
        self.label_orbitalperiod = QtWidgets.QLabel(self.centralwidget)
        self.label_orbitalperiod.setGeometry(QtCore.QRect(140, 400, 101, 16))
        self.label_orbitalperiod.setObjectName("label_orbitalperiod")
        self.label_diameter = QtWidgets.QLabel(self.centralwidget)
        self.label_diameter.setGeometry(QtCore.QRect(330, 300, 91, 16))
        self.label_diameter.setObjectName("label_diameter")
        self.label_climate = QtWidgets.QLabel(self.centralwidget)
        self.label_climate.setGeometry(QtCore.QRect(330, 350, 101, 16))
        self.label_climate.setObjectName("label_climate")
        self.label_gravity = QtWidgets.QLabel(self.centralwidget)
        self.label_gravity.setGeometry(QtCore.QRect(330, 400, 91, 16))
        self.label_gravity.setObjectName("label_gravity")
        self.label_terrain = QtWidgets.QLabel(self.centralwidget)
        self.label_terrain.setGeometry(QtCore.QRect(530, 290, 101, 41))
        self.label_terrain.setWordWrap(True)
        self.label_terrain.setObjectName("label_terrain")
        self.label_surfacewater = QtWidgets.QLabel(self.centralwidget)
        self.label_surfacewater.setGeometry(QtCore.QRect(530, 350, 101, 16))
        self.label_surfacewater.setObjectName("label_surfacewater")
        self.label_population = QtWidgets.QLabel(self.centralwidget)
        self.label_population.setGeometry(QtCore.QRect(530, 400, 101, 16))
        self.label_population.setObjectName("label_population")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name_header.setText(_translate("MainWindow", "Luke Skywalker"))
        self.label_2.setText(_translate("MainWindow", "Height:"))
        self.label_3.setText(_translate("MainWindow", "Mass:"))
        self.label_4.setText(_translate("MainWindow", "Hair Color:"))
        self.label_5.setText(_translate("MainWindow", "Skin Color:"))
        self.label_6.setText(_translate("MainWindow", "Eye Color:"))
        self.label_7.setText(_translate("MainWindow", "Birth Year:"))
        self.label_8.setText(_translate("MainWindow", "Gender:"))
        self.label_9.setText(_translate("MainWindow", "Homeworld:-"))
        self.label_10.setText(_translate("MainWindow", "Name:"))
        self.label_11.setText(_translate("MainWindow", "Rotation Period:"))
        self.label_12.setText(_translate("MainWindow", "Orbital Period:"))
        self.label_13.setText(_translate("MainWindow", "Diameter:"))
        self.label_14.setText(_translate("MainWindow", "Climate:"))
        self.label_15.setText(_translate("MainWindow", "Gravity:"))
        self.label_16.setText(_translate("MainWindow", "Terrain:"))
        self.label_17.setText(_translate("MainWindow", "Surface Water:"))
        self.label_18.setText(_translate("MainWindow", "Population:"))
        self.label_height.setText(_translate("MainWindow", "TextLabel"))
        self.label_mass.setText(_translate("MainWindow", "TextLabel"))
        self.label_gender.setText(_translate("MainWindow", "TextLabel"))
        self.label_haircolor.setText(_translate("MainWindow", "TextLabel"))
        self.label_skincolor.setText(_translate("MainWindow", "TextLabel"))
        self.label_eyecolor.setText(_translate("MainWindow", "TextLabel"))
        self.label_birthyear.setText(_translate("MainWindow", "TextLabel"))
        self.label_name.setText(_translate("MainWindow", "TextLabel"))
        self.label_rotationperiod.setText(_translate("MainWindow", "TextLabel"))
        self.label_orbitalperiod.setText(_translate("MainWindow", "TextLabel"))
        self.label_diameter.setText(_translate("MainWindow", "TextLabel"))
        self.label_climate.setText(_translate("MainWindow", "TextLabel"))
        self.label_gravity.setText(_translate("MainWindow", "TextLabel"))
        self.label_terrain.setText(_translate("MainWindow", "TextLabel"))
        self.label_surfacewater.setText(_translate("MainWindow", "TextLabel"))
        self.label_population.setText(_translate("MainWindow", "TextLabel"))

    def name_label_header(self, name):
        self.name_header.setText(name)

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
